# Generated by Django 3.2.3 on 2021-06-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(db_index=True, default='', max_length=255)),
                ('stock_code', models.CharField(db_index=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(db_index=True, default='', max_length=255)),
                ('stock_code', models.CharField(db_index=True, default='', max_length=255)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('opening_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('previous_closing_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('percent_change', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('absolute_change', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('day_high_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('day_low_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('high_52week_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('low_52week_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_traded_volume', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('upper_circuit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('lower_circuit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('delivery_to_traded_quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, default='', max_length=255)),
                ('stock_list', models.ManyToManyField(blank=True, related_name='stock_list', to='stock_api.StockDetails')),
            ],
        ),
    ]
