# Generated by Django 3.2.3 on 2021-05-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(db_index=True, default='', max_length=255)),
                ('stock_code', models.CharField(db_index=True, default='', max_length=255)),
            ],
        ),
    ]
